# Generated by Django 5.2.1 on 2025-05-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Sport', 'Sport'), ('SUV', 'SUV'), ('MPV', 'MPV'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Diesel', 'Diesel')], max_length=10)),
                ('fuel_capacity', models.PositiveIntegerField(help_text='Capacidade do tanque em litros')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_position', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car')),
            ],
        ),
    ]
